mailman:
  image: catatnight/postfix
  environment:
    maildomain: "mail.example.com"
    smtp_user: "user:password"
  ports:
    - "25:25"

mongodb:
  image: mongo:3
  ports:
    - "27017"
  volumes:
    - /data/db

master:
  build: .
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
  ports:
    - "50000:50000"
    - "80:8080"
  volumes:
    - /var/jenkins_home
  links:
    - mailman
    - mongodb
