master:
  build: .
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
  ports:
    - "50000:50000"
    - "80:8080"
  volumes_from:
    - config
  links:
    - mailman
    - mongodb

config:
  build: .
  entrypoint: /bin/echo
  volumes:
    - /var/jenkins_home
